"""AUTO-GENERATED by scripts/spec_cli.py — do not edit.

Source: agents/routing_navigator/spec.yaml (reward block).
Regenerate: `python scripts/spec_cli.py generate-reward-config`.
"""

from __future__ import annotations

WEIGHTS: dict[str, float] = {
    "w_fairness": 0.15,
    "w_freshness": 0.25,
    "w_fuel": 0.2,
    "w_time": 0.4,
}

SCALE: float = 1.0
