"""AUTO-GENERATED by scripts/spec_cli.py — do not edit.

Source: agents/freshness_guardian/spec.yaml (reward block).
Regenerate: `python scripts/spec_cli.py generate-reward-config`.
"""

from __future__ import annotations

WEIGHTS: dict[str, float] = {
    "accuracy_weight": 1.0,
    "fssai_weight": 2.0,
    "timing_weight": 0.4,
    "unnecessary_weight": 0.3,
}

SCALE: float = 1.0
