"""AUTO-GENERATED by scripts/spec_cli.py — do not edit.

Source: agents/demand_prophet/spec.yaml (reward block).
Regenerate: `python scripts/spec_cli.py generate-reward-config`.
"""

from __future__ import annotations

WEIGHTS: dict[str, float] = {
    "calibration_weight": 0.5,
    "crps_weight": 1.0,
    "event_weight": 0.1,
}

SCALE: float = 1.0
