/**
 * SYNAPSE Atlas Console — TanStack Router instance.
 *
 * The route tree is generated by @tanstack/router-vite-plugin from files
 * under src/surfaces/. We import that generated tree here and create a
 * single Router instance.
 *
 * Route preloading is set to "intent" (hover) for desktop ops use; ops
 * controllers traverse a known set of surfaces and benefit from the latency
 * win. Mobile defaults to "viewport" so we don't burn data on hover-only.
 */
import { createRouter } from "@tanstack/react-router";
import { QueryClient } from "@tanstack/react-query";

import { routeTree } from "../routeTree.gen";

export interface RouterContext {
  readonly queryClient: QueryClient;
}

export function createAppRouter(queryClient: QueryClient) {
  return createRouter({
    routeTree,
    context: { queryClient } satisfies RouterContext,
    defaultPreload: "intent",
    defaultPreloadStaleTime: 0,
    scrollRestoration: true,
    defaultErrorComponent: ({ error }) => (
      <div role="alert" className="p-6 text-safety-critical">
        <h2 className="text-ops-lg font-semibold">Something went wrong.</h2>
        <pre className="mt-2 text-ops-xs text-muted-fg">
          {error instanceof Error ? error.message : String(error)}
        </pre>
      </div>
    ),
    defaultNotFoundComponent: () => (
      <div role="alert" className="p-6">
        <h2 className="text-ops-lg font-semibold">Route not found.</h2>
        <p className="mt-2 text-ops-sm text-muted-fg">
          Try going back to the home page.
        </p>
      </div>
    ),
  });
}

export type AppRouter = ReturnType<typeof createAppRouter>;

declare module "@tanstack/react-router" {
  interface Register {
    router: AppRouter;
  }
}
