"""AUTO-GENERATED by scripts/spec_cli.py — do not edit.

Source: agents/supplier_trust/spec.yaml (reward block).
Regenerate: `python scripts/spec_cli.py generate-reward-config`.
"""

from __future__ import annotations

WEIGHTS: dict[str, float] = {
}

SCALE: float = 1.0
