apiVersion: v1
kind: ServiceAccount
metadata:
  name: supplier-trust
  labels:
    app: supplier-trust
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
