"""AUTO-GENERATED by scripts/spec_cli.py — do not edit.

Source: agents/sustainability_agent/spec.yaml (reward block).
Regenerate: `python scripts/spec_cli.py generate-reward-config`.
"""

from __future__ import annotations

WEIGHTS: dict[str, float] = {
    "accuracy_weight": 0.3,
    "carbon_weight": 1.0,
    "waste_weight": 0.5,
}

SCALE: float = 1.0
