"""AUTO-GENERATED by scripts/spec_cli.py — do not edit.

Source: agents/pricing_oracle/spec.yaml (reward block).
Regenerate: `python scripts/spec_cli.py generate-reward-config`.
"""

from __future__ import annotations

WEIGHTS: dict[str, float] = {
    "competitor_gap_weight": -2.0,
    "elasticity_weight": 0.5,
    "essential_penalty_weight": -5.0,
    "revenue_weight": 1.0,
}

SCALE: float = 1.0
