apiVersion: v1
kind: ServiceAccount
metadata:
  name: pricing-oracle
  labels:
    app: pricing-oracle
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
