apiVersion: v1
kind: ServiceAccount
metadata:
  name: sustainability-agent
  labels:
    app: sustainability-agent
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
