"""Property-based test for honest HITL timeout records (task 8.10, design E3).

Feature: purpose-achievement-audit, Property 25: Timeout records match dispatch reality

    *For any* timeout action and *any* resolution ordering of concurrently outstanding
    escalations, ``human_override`` records a dispatched action only when a matching
    entry exists in ``execution_confirmations``, a timed-out escalation is resolved with
    no pending entry retained for its decision identifier, a response addressed to
    either outstanding identifier is accepted, and resolving one escalation dispatches
    nothing for the other.

Why the property is shaped this way
-----------------------------------

Requirement 5's secondary finding is an I-7 wording breach: ``EXECUTE_TIER1`` and
``EXECUTE_LAST_KNOWN_GOOD`` wrote ``human_override = {"action": "timeout_<name>"}`` while
``escalate`` only awaits a human future and dispatches nothing, so the audit row named an
action nobody performed. Task 8.9 made the claim *derived* instead of asserted:
``dispatched`` comes from the decision's own ``execution_confirmations`` through
``has_dispatch_confirmation``, and the requested fallback is named only when that evidence
exists. ``orchestrator/tests/test_escalation.py`` pins that at four examples. Three
failure modes survive any fixed set of examples:

1. **A fabricated dispatch.** The claim is correct for the examples chosen and wrong for
   some other evidence shape - a padded or upper-cased status, an ``error:`` entry
   alongside a real one, an absence status the vocabulary forgot. The property drives
   *sets* of evidence whose meaning is known from how each entry was generated, so a
   classifier that guesses is caught rather than agreed with.
2. **A leaked pending entry.** ``_resolve_pending`` runs in a ``finally``, so a single
   escalation always looks clean. What a single escalation cannot show is that resolving
   one removed *exactly* one entry: the property asserts the pending set before and after
   every resolution, so a removal that drops two entries, none, or the wrong one fails.
3. **Cross-talk between outstanding escalations.** The example test resolves two
   escalations in one fixed order. The property permutes the resolution order over two to
   four concurrent escalations and asserts, at each step, that no other escalation
   completed and that the pending set is exactly the identifiers not yet resolved.

Independent oracle
------------------

``dispatched`` is never checked against a re-run of the subject's own classifier. Every
generated confirmation entry is drawn from one of two vocabularies declared *here*:
``ABSENCE_STATUSES`` plus ``error:``-prefixed entries record an absence of enacted work,
and ``ENACTED_STATUSES`` record work an agent actually performed (the shapes
``_phase_execute`` writes: an agent's ``status`` field, ``no_result`` when a response
carried none, ``error:<exc>`` when the hop raised - ``protocol.py:1517``). The expected
verdict is therefore a property of *how the example was built*, and the subject is
compared against that provenance. Duplicating the absence vocabulary is deliberate: if a
status is dropped from the module's set, ``unknown`` starts counting as a dispatch, and
under I-7 that is exactly the regression this file must fail on.

``diverged`` is generated by neither pool. ``sustainability_agent`` returns it with empty
``world_effects``, which the audit credits as honest non-action, yet
``_NON_DISPATCH_CONFIRMATIONS`` does not list it - so a ``diverged`` confirmation would
currently read as an enacted dispatch. That is a live cross-cutting question for the
owner of ``escalation.py``; this property neither blesses nor condemns it, and says so
rather than encoding a guess.

Cost, and why this is not slow-marked
-------------------------------------

Every timeout is driven through the injected ``HumanResponseWaiter`` seam, gated on an
``asyncio.Event``: the configured bound is *reported* and never awaited, so no example
sleeps and the ordering of timeouts against human responses is generated rather than
raced. Completion is settled by a bounded number of scheduler turns, so a regression
fails instead of hanging - there is no watchdog and therefore no wall clock anywhere in
this file. Nothing here constructs ``ConsensusProtocol``, drives the SimPy twin, opens a
socket, or touches Postgres, so the test carries no ``@pytest.mark.slow`` and runs in
``ci.yml::quality-gates`` with the rest of ``orchestrator/tests``.

Async style
-----------

``orchestrator/tests/test_escalation.py`` drives ``escalate`` with plain ``asyncio`` -
``create_task``, ``receive_human_response``, and a scripted timer-free waiter. This file
drives that same shape. Hypothesis owns the test function, so each example enters the
loop through one ``asyncio.run`` call, which is what the repo's other async property
tests do (``orchestrator/tests/consensus/test_append_only_pbt.py:222``,
``test_debate_concession_pbt.py:283``). No new async framework, no event-loop fixture,
and no ``@given`` layered on ``@pytest.mark.asyncio`` under ``asyncio_mode = "strict"``.

Every timeout bound in this file comes from an ``OrchestratorConfig`` instance and the
generated range is derived from the configured default, so no seconds literal appears
here. ``max_examples`` is never set - the budget comes from the root ``conftest.py``
profiles (``dev``=10, ``heavy``=100, ``ci``/``default``=500, ``nightly``=5000).

**Validates: Requirements 5.5, 5.8, 5.9**
"""

from __future__ import annotations

import asyncio
import json
from typing import TYPE_CHECKING, Any, Final, NamedTuple
from uuid import UUID

from hypothesis import given
from hypothesis import strategies as st
from synapse_common.models import ConsensusDecision, DecisionTier, HitlTimeoutAction

from orchestrator.config import OrchestratorConfig
from orchestrator.hitl.escalation import (
    TIMEOUT_DEFERRED,
    TIMEOUT_NO_ACTION,
    HITLEscalation,
    WebSocketManager,
    build_timeout_record,
    has_dispatch_confirmation,
)

if TYPE_CHECKING:
    from collections.abc import Sequence

# --------------------------------------------------------------------------- constants

#: Statuses that record an *absence* of enacted work. Declared here, not imported, so the
#: oracle is independent of the set the subject classifies against (I-7).
ABSENCE_STATUSES: Final[tuple[str, ...]] = (
    "",
    "blocked",
    "deferred",
    "failed",
    "no_result",
    "rejected",
    "skipped",
    "unknown",
    "withheld",
)

#: Statuses an agent returns when it did enact its ratified proposal. ``ok`` is the shape
#: ``orchestrator/tests/consensus/test_dispatch_choke_point.py:222`` observes on a real
#: dispatch; the rest are the same class of report.
ENACTED_STATUSES: Final[tuple[str, ...]] = (
    "actuated",
    "applied",
    "completed",
    "confirmed",
    "executed",
    "ok",
    "success",
)

#: Generated by neither pool - see the module docstring. ``diverged`` is an open
#: cross-cutting question owned by ``escalation.py``, not a claim this property makes.
UNCLASSIFIED_STATUSES: Final[tuple[str, ...]] = ("diverged",)

#: The prefix ``_phase_execute`` writes when the execution hop raised.
ERROR_PREFIX: Final[str] = "error:"

#: I-5 is stated without qualification, so no assertion here may depend on the route.
TIERS: Final[tuple[DecisionTier, ...]] = tuple(DecisionTier)

#: Every configurable fallback, including the two whose names imply execution.
TIMEOUT_ACTIONS: Final[tuple[HitlTimeoutAction, ...]] = tuple(HitlTimeoutAction)

#: The shipped HITL bound, read from configuration. No seconds literal appears below.
DEFAULT_TIMEOUT_SECONDS: Final[float] = OrchestratorConfig().hitl_timeout_seconds

#: Event-loop turns allowed for every escalation to register its pending entry, and for
#: one released escalation to finish. A turn bound rather than a wall-clock watchdog: a
#: regression fails the example instead of sleeping on it (I-0).
MAX_SCHEDULER_TURNS: Final[int] = 16

#: Alphabet for generated free text (exception details, operator notes). ASCII only.
DETAIL_ALPHABET: Final[str] = "abcdefghijklmnopqrstuvwxyz -_"

#: Identifier space for generated decision ids. ``UUID(int=n)`` keeps examples
#: reproducible where ``uuid4`` would not.
ID_SPACE: Final[int] = 2**32


# ------------------------------------------------------------------------ generated data


class Evidence(NamedTuple):
    """Generated ``execution_confirmations`` plus what they mean by construction."""

    entries: tuple[str, ...]
    #: True iff at least one entry was drawn from ``ENACTED_STATUSES``.
    enacted: bool


class Outstanding(NamedTuple):
    """One escalation awaiting resolution, and how it is scripted to resolve."""

    decision: ConsensusDecision
    enacted: bool
    times_out: bool
    response: dict[str, Any]


class EscalationCase(NamedTuple):
    """Concurrently outstanding escalations, a configuration, and a resolution order."""

    settings: OrchestratorConfig
    escalations: tuple[Outstanding, ...]
    order: tuple[UUID, ...]


# ------------------------------------------------------------------------ observations


class Resolution(NamedTuple):
    """What was observable around one escalation's resolution."""

    decision_id: UUID
    timed_out: bool
    result: ConsensusDecision | None
    pending_before: frozenset[UUID]
    pending_after: frozenset[UUID]
    #: Identifiers not yet resolved once this one has been.
    still_outstanding: frozenset[UUID]
    #: Other escalations whose task had completed at this point ...
    completed_others: frozenset[UUID]
    #: ... and the only ones that legitimately could have: those resolved earlier.
    expected_completed_others: frozenset[UUID]
    #: Whether the human response was accepted (``None`` for a timed-out resolution).
    response_accepted: bool | None
    #: Whether a *second* response to the same identifier was accepted after resolution.
    late_response_accepted: bool


class DriveReport(NamedTuple):
    """Everything one driven case observed, asserted by the properties below."""

    registered: frozenset[UUID]
    resolutions: tuple[Resolution, ...]
    pending_at_end: tuple[UUID, ...]
    #: ``(kafka key, decision_id in the published payload)`` per escalation.
    published: tuple[tuple[str, str], ...]
    #: The bound handed to the waiter for each escalation - reported, never awaited.
    reported_bounds: tuple[float, ...]


# ------------------------------------------------------------------------- test doubles


class RecordingProducer:
    """A Kafka producer stand-in: records what was published and publishes nothing."""

    __slots__ = ("published",)

    def __init__(self) -> None:
        self.published: list[tuple[str, str]] = []

    def produce(self, topic: str, *, value: dict[str, Any], key: str) -> None:
        del topic
        self.published.append((key, str(value.get("decision_id", ""))))


class GatedWaiter:
    """The ``HumanResponseWaiter`` seam, driven by events instead of by a clock.

    Identifiers in *timeout_for* raise ``TimeoutError``, but only once the driver releases
    them, so *when* a timeout lands relative to a human response is generated rather than
    raced. ``timeout`` is recorded and never slept on.
    """

    __slots__ = ("_gates", "_timeout_for", "reported_bounds")

    def __init__(self, timeout_for: frozenset[UUID]) -> None:
        self._timeout_for: frozenset[UUID] = timeout_for
        self._gates: dict[UUID, asyncio.Event] = {}
        self.reported_bounds: list[float] = []

    def _gate(self, decision_id: UUID) -> asyncio.Event:
        gate = self._gates.get(decision_id)
        if gate is None:
            gate = asyncio.Event()
            self._gates[decision_id] = gate
        return gate

    def release(self, decision_id: UUID) -> None:
        """Let the escalation for *decision_id* time out now."""
        self._gate(decision_id).set()

    async def __call__(
        self,
        future: asyncio.Future[dict[str, Any]],
        *,
        timeout: float,
        decision_id: UUID,
    ) -> dict[str, Any]:
        self.reported_bounds.append(timeout)
        if decision_id in self._timeout_for:
            await self._gate(decision_id).wait()
            raise TimeoutError
        return await future


# --------------------------------------------------------------------------- strategies


def varied(draw: st.DrawFn, status: str) -> str:
    """Case- and whitespace-vary *status*: the classifier strips and lowercases."""
    lead = draw(st.sampled_from(("", " ", "\t")))
    trail = draw(st.sampled_from(("", " ", "\n")))
    body = status.upper() if draw(st.booleans()) else status
    return f"{lead}{body}{trail}"


@st.composite
def absence_entries(draw: st.DrawFn) -> str:
    """One confirmation entry that records an absence of enacted work."""
    if draw(st.booleans()):
        return varied(draw, draw(st.sampled_from(ABSENCE_STATUSES)))
    detail = draw(st.text(alphabet=DETAIL_ALPHABET, max_size=12))
    return varied(draw, f"{ERROR_PREFIX}{detail}")


@st.composite
def enacted_entries(draw: st.DrawFn) -> str:
    """One confirmation entry that names work an agent actually enacted."""
    return varied(draw, draw(st.sampled_from(ENACTED_STATUSES)))


@st.composite
def evidence(draw: st.DrawFn) -> Evidence:
    """Confirmations whose meaning is known from the pool each entry came from."""
    absences = draw(st.lists(absence_entries(), max_size=3))
    enacted = draw(st.lists(enacted_entries(), max_size=2))
    entries = draw(st.permutations([*absences, *enacted]))
    return Evidence(entries=tuple(entries), enacted=bool(enacted))


def timeout_actions() -> st.SearchStrategy[HitlTimeoutAction]:
    """Every configurable timeout fallback, including the two that imply execution."""
    return st.sampled_from(TIMEOUT_ACTIONS)


def configured_bounds() -> st.SearchStrategy[float]:
    """Bounds derived from the configured default - the shipped value plus a spread."""
    return st.one_of(
        st.just(DEFAULT_TIMEOUT_SECONDS),
        st.floats(
            min_value=DEFAULT_TIMEOUT_SECONDS / 100.0,
            max_value=DEFAULT_TIMEOUT_SECONDS * 10.0,
            allow_nan=False,
            allow_infinity=False,
        ),
    )


@st.composite
def hitl_settings(draw: st.DrawFn) -> OrchestratorConfig:
    """Configuration carrying the HITL bound and fallback the escalator is built with."""
    return OrchestratorConfig(
        hitl_timeout_seconds=draw(configured_bounds()),
        hitl_timeout_action=str(draw(timeout_actions()).value),
    )


def confidences() -> st.SearchStrategy[float]:
    """Any confidence a ``ConsensusDecision`` admits (the model pins ``0 <= c <= 1``)."""
    return st.floats(min_value=0.0, max_value=1.0, allow_nan=False, allow_infinity=False)


def human_responses() -> st.SearchStrategy[dict[str, Any]]:
    """What a human sends: an approval, a rejection, or a modification."""
    return st.fixed_dictionaries(
        {"action": st.sampled_from(("approved", "rejected", "modified"))},
        optional={"notes": st.text(alphabet=DETAIL_ALPHABET, max_size=12)},
    )


def outstanding_decision(
    decision_id: UUID,
    tier: DecisionTier,
    confidence: float,
    confirmations: Sequence[str],
) -> ConsensusDecision:
    """A decision carrying exactly the generated confirmations and no other evidence."""
    return ConsensusDecision(
        decision_id=decision_id,
        tier=tier,
        proposals=[],
        selected_action={},
        pareto_weights={"demand_accuracy": 1.0},
        confidence=confidence,
        audit_trace=["property-25"],
        execution_confirmations=list(confirmations),
    )


@st.composite
def escalation_cases(draw: st.DrawFn) -> EscalationCase:
    """Two to four concurrent escalations, at least one of which times out.

    R5.9 is about what happens *while* escalations are outstanding together, so a case is
    never a single escalation. The resolution order is a generated permutation, which is
    what makes "resolving one never resolves another" falsifiable in both directions.
    """
    settings = draw(hitl_settings())
    raw_ids = draw(
        st.lists(
            st.integers(min_value=1, max_value=ID_SPACE),
            min_size=2,
            max_size=4,
            unique=True,
        ),
    )
    identifiers = [UUID(int=raw) for raw in raw_ids]

    shuffled = draw(st.permutations(identifiers))
    timing_out = frozenset(shuffled[: draw(st.integers(min_value=1, max_value=len(identifiers)))])

    escalations: list[Outstanding] = []
    for decision_id in identifiers:
        found = draw(evidence())
        escalations.append(
            Outstanding(
                decision=outstanding_decision(
                    decision_id,
                    draw(st.sampled_from(TIERS)),
                    draw(confidences()),
                    found.entries,
                ),
                enacted=found.enacted,
                times_out=decision_id in timing_out,
                response=draw(human_responses()),
            ),
        )

    return EscalationCase(
        settings=settings,
        escalations=tuple(escalations),
        order=tuple(draw(st.permutations(identifiers))),
    )


# ------------------------------------------------------------------------------- driver


async def settle(task: asyncio.Task[ConsensusDecision]) -> ConsensusDecision | None:
    """Let *task* finish using scheduler turns only - never the clock.

    Returns ``None`` when the escalation did not finish within the bound, so a hang
    surfaces as a failed assertion in the property rather than as a stalled test run.
    """
    for _ in range(MAX_SCHEDULER_TURNS):
        if task.done():
            return await task
        await asyncio.sleep(0)
    task.cancel()
    return None


async def drive(case: EscalationCase) -> DriveReport:
    """Escalate every decision, resolve them in the generated order, observe as we go."""
    waiter = GatedWaiter(
        frozenset(entry.decision.decision_id for entry in case.escalations if entry.times_out),
    )
    producer = RecordingProducer()
    escalator = HITLEscalation(
        kafka_producer=producer,
        ws_manager=WebSocketManager(),
        timeout_seconds=case.settings.hitl_timeout_seconds,
        timeout_action=case.settings.hitl_timeout_action,
        waiter=waiter,
    )

    by_id = {entry.decision.decision_id: entry for entry in case.escalations}
    tasks: dict[UUID, asyncio.Task[ConsensusDecision]] = {
        entry.decision.decision_id: asyncio.create_task(escalator.escalate(entry.decision))
        for entry in case.escalations
    }

    # Every escalation registers its pending entry before the first resolution.
    for _ in range(MAX_SCHEDULER_TURNS):
        if len(escalator.pending_decision_ids()) == len(tasks):
            break
        await asyncio.sleep(0)
    registered = frozenset(escalator.pending_decision_ids())

    all_ids = frozenset(tasks)
    resolved: set[UUID] = set()
    resolutions: list[Resolution] = []

    for decision_id in case.order:
        entry = by_id[decision_id]
        pending_before = frozenset(escalator.pending_decision_ids())

        accepted: bool | None = None
        if entry.times_out:
            waiter.release(decision_id)
        else:
            accepted = await escalator.receive_human_response(decision_id, dict(entry.response))

        result = await settle(tasks[decision_id])
        pending_after = frozenset(escalator.pending_decision_ids())
        late = await escalator.receive_human_response(decision_id, dict(entry.response))
        resolved.add(decision_id)

        resolutions.append(
            Resolution(
                decision_id=decision_id,
                timed_out=entry.times_out,
                result=result,
                pending_before=pending_before,
                pending_after=pending_after,
                still_outstanding=all_ids - resolved,
                completed_others=frozenset(
                    other for other, task in tasks.items() if other != decision_id and task.done()
                ),
                expected_completed_others=frozenset(resolved - {decision_id}),
                response_accepted=accepted,
                late_response_accepted=late,
            ),
        )

    await asyncio.gather(*tasks.values(), return_exceptions=True)

    return DriveReport(
        registered=registered,
        resolutions=tuple(resolutions),
        pending_at_end=escalator.pending_decision_ids(),
        published=tuple(producer.published),
        reported_bounds=tuple(waiter.reported_bounds),
    )


# -------------------------------------------------------------------------- properties


# Feature: purpose-achievement-audit, Property 25: Timeout records match dispatch reality
@given(requested=timeout_actions(), found=evidence(), settings=hitl_settings())
def test_a_timeout_record_claims_a_dispatch_only_with_a_matching_confirmation(
    requested: HitlTimeoutAction,
    found: Evidence,
    settings: OrchestratorConfig,
) -> None:
    """R5.5: ``dispatched`` is derived from the evidence, and names the fallback only then."""
    bound = settings.hitl_timeout_seconds
    record = build_timeout_record(
        requested=requested,
        timeout_seconds=bound,
        confirmations=found.entries,
    )
    override = record.to_override()

    # The classifier agrees with how the example was built - not with itself.
    assert has_dispatch_confirmation(found.entries) is found.enacted
    assert record.dispatched is found.enacted
    assert override["dispatched"] is found.enacted

    named_as_performed = f"timeout_{requested.value}"
    if found.enacted:
        assert record.action == named_as_performed
    else:
        # I-7: no matching entry, so the record must not name the action as performed.
        assert record.action != named_as_performed
        assert record.action in {TIMEOUT_NO_ACTION, TIMEOUT_DEFERRED}
        assert (record.action == TIMEOUT_DEFERRED) is (requested is HitlTimeoutAction.DEFER)

    # The request is reported faithfully whichever way the evidence fell.
    assert record.requested is requested
    assert override["requested"] == requested.value
    assert override["action"] == record.action

    # The reason names the configured bound - the bound is reported, never awaited.
    assert str(bound) in str(override["reason"])

    # The override is a persisted payload: canonical bytes round-trip (repo convention).
    canonical = json.dumps(override, sort_keys=True, separators=(",", ":"))
    assert json.loads(canonical) == override


# Feature: purpose-achievement-audit, Property 25: Timeout records match dispatch reality
@given(
    requested=timeout_actions(),
    entries=st.one_of(st.none(), st.lists(absence_entries(), max_size=4)),
    settings=hitl_settings(),
)
def test_absent_evidence_is_never_read_as_a_dispatch(
    requested: HitlTimeoutAction,
    entries: list[str] | None,
    settings: OrchestratorConfig,
) -> None:
    """R5.5 under I-7: absence of proof is never proof - ``None`` included."""
    record = build_timeout_record(
        requested=requested,
        timeout_seconds=settings.hitl_timeout_seconds,
        confirmations=entries,
    )

    assert has_dispatch_confirmation(entries) is False
    assert record.dispatched is False
    assert record.action != f"timeout_{requested.value}"
    assert record.action in {TIMEOUT_NO_ACTION, TIMEOUT_DEFERRED}
    assert record.to_override()["dispatched"] is False
    assert record.requested is requested


# Feature: purpose-achievement-audit, Property 25: Timeout records match dispatch reality
@given(case=escalation_cases())
def test_an_escalation_timeout_dispatches_nothing_and_records_exactly_that(
    case: EscalationCase,
) -> None:
    """R5.5 through ``escalate``: for any timeout ordering, the record matches reality."""
    report = asyncio.run(drive(case))
    by_id = {entry.decision.decision_id: entry for entry in case.escalations}
    configured = str(case.settings.hitl_timeout_action)
    named_as_performed = f"timeout_{configured}"

    assert report.registered == frozenset(by_id)
    assert len(report.resolutions) == len(case.escalations)

    # The configured bound reached the waiter once per escalation and was never slept on.
    assert len(report.reported_bounds) == len(case.escalations)
    assert set(report.reported_bounds) == {case.settings.hitl_timeout_seconds}

    # One escalation published per decision, each keyed by the decision it names.
    assert len(report.published) == len(case.escalations)
    assert all(key == payload_id for key, payload_id in report.published)
    assert {key for key, _ in report.published} == {str(known) for known in by_id}

    for resolution in report.resolutions:
        entry = by_id[resolution.decision_id]
        result = resolution.result
        assert result is not None
        assert result.escalated_to_human is True

        override = result.human_override
        assert override is not None

        # Escalating enacts nothing on either branch: the evidence is untouched.
        assert result.execution_confirmations == entry.decision.execution_confirmations

        if not resolution.timed_out:
            assert override == entry.response
            assert "dispatched" not in override
            continue

        assert override["dispatched"] is entry.enacted
        assert has_dispatch_confirmation(result.execution_confirmations) is entry.enacted
        assert override["requested"] == configured

        if entry.enacted:
            assert result.execution_confirmations != []
            assert override["action"] == named_as_performed
        else:
            assert override["action"] != named_as_performed
            assert override["action"] in {TIMEOUT_NO_ACTION, TIMEOUT_DEFERRED}


# Feature: purpose-achievement-audit, Property 25: Timeout records match dispatch reality
@given(case=escalation_cases())
def test_a_resolved_escalation_leaves_the_pending_set_exactly_once(
    case: EscalationCase,
) -> None:
    """R5.8: the timed-out escalation is resolved and retains no pending entry."""
    report = asyncio.run(drive(case))

    for resolution in report.resolutions:
        assert resolution.result is not None
        assert resolution.decision_id in resolution.pending_before

        # Exactly one entry left the pending set, and it was this identifier's.
        assert resolution.pending_before - resolution.pending_after == {resolution.decision_id}
        assert len(resolution.pending_before) - len(resolution.pending_after) == 1
        assert resolution.decision_id not in resolution.pending_after

        # No ghost entry survives: a second response finds nothing left to resolve.
        assert resolution.late_response_accepted is False

    assert report.pending_at_end == ()


# Feature: purpose-achievement-audit, Property 25: Timeout records match dispatch reality
@given(case=escalation_cases())
def test_outstanding_escalations_resolve_independently(case: EscalationCase) -> None:
    """R5.9: a response is accepted for either identifier, and one resolution is local."""
    report = asyncio.run(drive(case))

    for resolution in report.resolutions:
        assert resolution.result is not None

        # Resolving this escalation completed no other one.
        assert resolution.completed_others == resolution.expected_completed_others

        # And dropped no other one: the pending set is exactly what is unresolved.
        assert resolution.pending_after == resolution.still_outstanding

        # While it was outstanding, a response addressed to it was accepted.
        if resolution.response_accepted is not None:
            assert resolution.response_accepted is True


# Feature: purpose-achievement-audit, Property 25: Timeout records match dispatch reality
@given(status=st.sampled_from(UNCLASSIFIED_STATUSES))
def test_the_unclassified_vocabulary_is_declared_rather_than_assumed(status: str) -> None:
    """Statuses this property refuses to judge are named, not silently excluded.

    ``diverged`` belongs to neither generated pool because the honest reading of it is an
    open question in ``escalation.py`` (see the module docstring). What is asserted here
    is only that the exclusion is deliberate: the status is in neither declared
    vocabulary, so no example above can have smuggled a guess about it into the oracle.
    """
    assert status not in ABSENCE_STATUSES
    assert status not in ENACTED_STATUSES
    assert not status.startswith(ERROR_PREFIX)
