apiVersion: apps/v1
kind: Deployment
metadata:
  name: demand-prophet
  labels:
    app: demand-prophet
    {{- range $k, $v := .Values.podLabels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: demand-prophet
  template:
    metadata:
      labels:
        app: demand-prophet
        {{- range $k, $v := .Values.podLabels }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: demand-prophet
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.global.imageTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: demand-prophet
  labels:
    app: demand-prophet
spec:
  selector:
    app: demand-prophet
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
