apiVersion: v1
kind: ServiceAccount
metadata:
  name: demand-prophet
  labels:
    app: demand-prophet
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
