apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-sentinel
  labels:
    app: inventory-sentinel
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
