#!/usr/bin/env python3
"""SYNAPSE Spec CLI — Sprint 8 promotion of ``agents/*/spec.yaml`` to source-of-truth.

WS-3 (ADR-027 phase 1, ADR-031). One argparse entrypoint with subcommands:

    synapse-spec validate                       (M1b)
    synapse-spec generate-tests                 (delegates to generate_tests_from_spec)
    synapse-spec generate-reward-config         (M3, shadow mode)
    synapse-spec generate-alerts                (M4)

Every generator supports ``--check`` so CI catches drift the same way Sprint 7's
``scripts/generate_burn_alerts.py --check`` does. Output is deterministic
(sorted keys, fixed float repr) so byte-comparison is a meaningful gate.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import TYPE_CHECKING, Any

import jsonschema
import yaml

if TYPE_CHECKING:
    from collections.abc import Iterable

REPO_ROOT = Path(__file__).resolve().parents[1]
SPEC_SCHEMA_PATH = REPO_ROOT / "docs" / "specs" / "agent_spec_schema.json"
AGENTS_DIR = REPO_ROOT / "agents"
PROM_RULES_DIR = REPO_ROOT / "infrastructure" / "prometheus" / "rules"
AUTOGEN_HEADER = (
    '"""AUTO-GENERATED by scripts/spec_cli.py — do not edit.\n\n'
    "Source: agents/{agent}/spec.yaml (reward block).\n"
    "Regenerate: `python scripts/spec_cli.py generate-reward-config`.\n"
    '"""\n'
)


# ---------- helpers -----------------------------------------------------------


def _agent_dirs() -> list[Path]:
    return sorted(p for p in AGENTS_DIR.iterdir() if p.is_dir() and (p / "spec.yaml").exists())


def _load_spec(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as fp:
        data: dict[str, Any] = yaml.safe_load(fp)
    return data


def _load_schema() -> dict[str, Any]:
    with SPEC_SCHEMA_PATH.open(encoding="utf-8") as fp:
        data: dict[str, Any] = json.load(fp)
    return data


def _format_float(value: float) -> str:
    """Deterministic float repr that survives Python version drift."""
    formatted = f"{value:.10g}"
    # Always include decimal point so floats are typed in the generated file.
    if "." not in formatted and "e" not in formatted:
        formatted = f"{formatted}.0"
    return formatted


def _emit_reward_config(agent: str, spec: dict[str, Any]) -> str:
    reward = spec.get("reward") or {}
    weights = reward.get("weights") or {}
    scale = reward.get("scale")
    lines = [
        AUTOGEN_HEADER.format(agent=agent),
        "from __future__ import annotations",
        "",
        "WEIGHTS: dict[str, float] = {",
    ]
    for key in sorted(weights.keys()):
        lines.append(f'    "{key}": {_format_float(float(weights[key]))},')
    lines.append("}")
    lines.append("")
    if scale is not None:
        lines.append(f"SCALE: float = {_format_float(float(scale))}")
    else:
        lines.append("SCALE: float = 1.0")
    lines.append("")
    return "\n".join(lines)


def _emit_alert_rules(spec: dict[str, Any]) -> dict[str, Any]:
    agent = spec["agent_name"]
    alerts = spec.get("alerts") or []
    invariants = {inv["id"]: inv for inv in spec.get("invariants", [])}

    rules: list[dict[str, Any]] = []
    for alert in alerts:
        inv_id = alert["invariant_id"]
        inv = invariants.get(inv_id, {})
        if inv.get("severity") != "critical":
            # Sprint 8 emits only critical-severity alerts; high/medium deferred to Sprint 9.
            continue
        op = {"gt": ">", "lt": "<", "ge": ">=", "le": "<=", "eq": "=="}[alert["comparison"]]
        threshold = _format_float(float(alert["threshold"]))
        expr = f"({alert['threshold_metric']}) {op} {threshold}"
        rule = {
            "alert": f"{agent}-{inv_id.lower()}",
            "expr": expr,
            "for": alert.get("window", "5m"),
            "labels": {
                "severity": alert.get("severity", "critical"),
                "agent": agent,
                "invariant": inv_id,
            },
            "annotations": {
                "summary": inv.get("description", inv_id),
                "runbook_url": alert.get(
                    "runbook",
                    f"https://github.com/Praneshrajan137/synapse/blob/main/docs/runbooks/{agent}_invariants.md",
                ),
            },
        }
        rules.append(rule)

    return {
        "groups": [
            {
                "name": f"synapse-{agent}-invariants",
                "interval": "30s",
                "rules": sorted(rules, key=lambda r: r["alert"]),
            }
        ]
    }


def _render_yaml(payload: dict[str, Any]) -> str:
    return yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)


def _diff_or_write(path: Path, rendered: str, check: bool) -> bool:
    """Return True on success / no drift. Writes when not in check mode."""
    if check:
        if not path.exists():
            print(f"missing {path.relative_to(REPO_ROOT)}", file=sys.stderr)
            return False
        existing = path.read_text(encoding="utf-8")
        if existing != rendered:
            print(f"out of sync: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(rendered, encoding="utf-8")
    print(f"wrote {path.relative_to(REPO_ROOT)}")
    return True


# ---------- subcommands -------------------------------------------------------


def cmd_validate(_args: argparse.Namespace) -> int:
    schema = _load_schema()
    errors: list[str] = []
    for agent_dir in _agent_dirs():
        spec_path = agent_dir / "spec.yaml"
        try:
            jsonschema.validate(_load_spec(spec_path), schema)
        except jsonschema.ValidationError as exc:
            errors.append(f"{spec_path.relative_to(REPO_ROOT)}: {exc.message}")
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1
    print(f"validated {len(_agent_dirs())} specs")
    return 0


def cmd_generate_tests(args: argparse.Namespace) -> int:
    from scripts.generate_tests_from_spec import main as gen_main  # type: ignore[import-not-found]

    # Delegate; existing CLI has --all flag.
    argv = ["--all"] if args.all else []
    return int(gen_main()) if not argv else int(gen_main())


def cmd_generate_reward_config(args: argparse.Namespace) -> int:
    """Emit reward_config.py for every agent that declares a ``reward:`` block.

    Sprint 9 (ADR-031 cutover): agents with empty ``reward.weights`` still
    get a generated file with ``WEIGHTS: dict[str, float] = {}`` so the
    contract is uniform across all 8 agents. inventory_sentinel and
    supplier_trust ride this path until Sprint 10 promotes their inline
    magic numbers to named weights.
    """
    success = True
    for agent_dir in _agent_dirs():
        agent = agent_dir.name
        spec = _load_spec(agent_dir / "spec.yaml")
        if not spec.get("reward"):
            continue
        training_dir = agent_dir / "training"
        if not training_dir.exists():
            continue
        rendered = _emit_reward_config(agent, spec)
        out_path = training_dir / "reward_config.py"
        if not _diff_or_write(out_path, rendered, args.check):
            success = False
    return 0 if success else 1


def cmd_generate_alerts(args: argparse.Namespace) -> int:
    success = True
    for agent_dir in _agent_dirs():
        agent = agent_dir.name
        spec = _load_spec(agent_dir / "spec.yaml")
        payload = _emit_alert_rules(spec)
        if not payload["groups"][0]["rules"]:
            # Sprint 8 cut: only emit when there are critical-severity rules.
            continue
        rendered = _render_yaml(payload)
        out_path = PROM_RULES_DIR / f"{agent}_invariants.yml"
        if not _diff_or_write(out_path, rendered, args.check):
            success = False
    return 0 if success else 1


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="synapse-spec")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser(
        "validate",
        help="Validate every agents/*/spec.yaml against agent_spec_schema.json",
    )

    p_tests = sub.add_parser("generate-tests", help="Regenerate test_spec.py files from spec.yaml")
    p_tests.add_argument("--all", action="store_true", default=True)

    p_reward = sub.add_parser(
        "generate-reward-config",
        help="Emit agents/<name>/training/reward_config.py from spec.reward.weights",
    )
    p_reward.add_argument("--check", action="store_true")

    p_alerts = sub.add_parser(
        "generate-alerts",
        help="Emit infrastructure/prometheus/rules/<agent>_invariants.yml from spec.alerts",
    )
    p_alerts.add_argument("--check", action="store_true")

    return parser


def main(argv: Iterable[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(list(argv) if argv is not None else None)
    if args.command == "validate":
        return cmd_validate(args)
    if args.command == "generate-tests":
        return cmd_generate_tests(args)
    if args.command == "generate-reward-config":
        return cmd_generate_reward_config(args)
    if args.command == "generate-alerts":
        return cmd_generate_alerts(args)
    parser.error(f"unknown command: {args.command}")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
