apiVersion: v1
kind: ServiceAccount
metadata:
  name: routing-navigator
  labels:
    app: routing-navigator
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
