/**
 * SYNAPSE Atlas Console — vite-plugin-agent-specs.
 *
 * Reads every `agents/<name>/spec.yaml` at build time, validates each
 * against `docs/specs/agent_spec_schema.json`, and emits a typed
 * virtual module:
 *
 *     import { agentSpecs } from "virtual:atlas/agent-specs";
 *
 * `agentSpecs` is a strongly-typed `AgentSpec[]` (see
 * src/types/atlas-agent-specs.d.ts). The Agent Floor surface renders
 * one panel per element. Adding a new agent is a one-PR exercise:
 * drop `agents/<name>/spec.yaml`, the panel materialises on the next
 * dev refresh.
 *
 * Why a virtual module instead of a generated file?
 *   - No file-system litter; the build output is the only artifact.
 *   - HMR-friendly: editing `agents/.../spec.yaml` re-emits the module
 *     and React Fast-Refresh swaps the panel in place.
 *
 * Failure modes (loud on purpose):
 *   - Missing `docs/specs/agent_spec_schema.json` → throws at config time.
 *   - YAML parse error → fails the build with the offending file path.
 *   - Schema validation failure → fails the build with the AJV diff.
 *
 * I-1: pure OSS deps (yaml MIT, ajv MIT). No paid SaaS schema service.
 * I-3: every agent's spec validates at the boundary the front-end consumes.
 */
import { readFileSync, readdirSync, statSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import Ajv, { type ValidateFunction } from "ajv";
import { parse as parseYaml } from "yaml";
import type { Plugin } from "vite";

export interface AgentSpecsPluginOptions {
  /** Repo root containing the `agents/` directory. */
  readonly repoRoot?: string;
  /** Path to docs/specs/agent_spec_schema.json. */
  readonly schemaPath?: string;
}

const VIRTUAL_ID = "virtual:atlas/agent-specs";
const RESOLVED_VIRTUAL_ID = `\0${VIRTUAL_ID}`;

export function agentSpecsPlugin(options: AgentSpecsPluginOptions = {}): Plugin {
  const __filename = fileURLToPath(import.meta.url);
  const pluginDir = dirname(__filename);
  const repoRoot = options.repoRoot ?? resolve(pluginDir, "..", "..");
  const schemaPath =
    options.schemaPath ?? resolve(repoRoot, "docs", "specs", "agent_spec_schema.json");

  let validate: ValidateFunction | null = null;
  let watchedFiles: string[] = [];

  function loadValidator(): ValidateFunction {
    if (validate) return validate;
    statSync(schemaPath);
    const schema = JSON.parse(readFileSync(schemaPath, "utf8"));
    const ajv = new Ajv({ allErrors: true, strict: false });
    validate = ajv.compile(schema);
    return validate;
  }

  function discoverSpecPaths(): string[] {
    const agentsDir = join(repoRoot, "agents");
    const out: string[] = [];
    let entries: string[];
    try {
      entries = readdirSync(agentsDir);
    } catch {
      return out;
    }
    for (const entry of entries) {
      const candidate = join(agentsDir, entry, "spec.yaml");
      try {
        if (statSync(candidate).isFile()) out.push(candidate);
      } catch {
        // No spec.yaml — skip silently. The agent might still be in
        // pre-spec scaffolding, which is allowed.
      }
    }
    out.sort();
    return out;
  }

  function loadSpec(absPath: string): unknown {
    const raw = readFileSync(absPath, "utf8");
    let doc: unknown;
    try {
      doc = parseYaml(raw);
    } catch (err) {
      throw new Error(
        `[atlas:agent-specs] YAML parse failed in ${relative(repoRoot, absPath)}: ${err instanceof Error ? err.message : String(err)}`,
      );
    }
    const v = loadValidator();
    if (!v(doc)) {
      const errs = (v.errors ?? [])
        .map((e) => `  · ${e.instancePath || "/"} ${e.message ?? ""}`)
        .join("\n");
      throw new Error(
        `[atlas:agent-specs] schema violation in ${relative(repoRoot, absPath)}:\n${errs}`,
      );
    }
    return doc;
  }

  function buildModuleSource(): string {
    const paths = discoverSpecPaths();
    watchedFiles = paths;
    const specs = paths.map((p) => loadSpec(p));
    // Deterministic JSON shape so the emitted module is reviewable in
    // bundle diffs. We sort top-level by `agent_name` so swapping order
    // in `agents/` doesn't shuffle the output.
    const sorted = (specs as { agent_name?: string }[])
      .slice()
      .sort((a, b) => String(a.agent_name ?? "").localeCompare(String(b.agent_name ?? "")));
    const json = JSON.stringify(sorted, null, 2);
    return [
      "// AUTO-GENERATED by vite-plugin-agent-specs.",
      "// Source of truth: agents/*/spec.yaml validated against",
      "// docs/specs/agent_spec_schema.json. Do not hand-edit.",
      `export const agentSpecs = Object.freeze(${json});`,
      "export default agentSpecs;",
    ].join("\n");
  }

  return {
    name: "atlas:agent-specs",
    enforce: "pre",

    async resolveId(id) {
      if (id === VIRTUAL_ID) return RESOLVED_VIRTUAL_ID;
      return null;
    },

    load(id) {
      if (id !== RESOLVED_VIRTUAL_ID) return null;
      return buildModuleSource();
    },

    configureServer(server) {
      const refresh = (): void => {
        try {
          buildModuleSource();
        } catch (err) {
          server.config.logger.error(
            (err instanceof Error ? err.message : String(err)) +
              "\n[atlas:agent-specs] keeping last known good module — HMR paused",
            { timestamp: true },
          );
          return;
        }
        const mod = server.moduleGraph.getModuleById(RESOLVED_VIRTUAL_ID);
        if (mod) {
          server.moduleGraph.invalidateModule(mod);
          server.ws.send({ type: "full-reload" });
        }
      };

      try {
        buildModuleSource();
      } catch (err) {
        server.config.logger.error(
          err instanceof Error ? err.message : String(err),
          { timestamp: true },
        );
      }
      for (const f of watchedFiles) server.watcher.add(f);
      server.watcher.add(schemaPath);
      // Watch the agents directory too so newly-added spec.yaml files trigger refresh.
      server.watcher.add(join(repoRoot, "agents"));

      server.watcher.on("change", (file) => {
        if (file.endsWith("spec.yaml") || file === schemaPath) refresh();
      });
      server.watcher.on("add", (file) => {
        if (file.endsWith("spec.yaml")) refresh();
      });
      server.watcher.on("unlink", (file) => {
        if (file.endsWith("spec.yaml")) refresh();
      });
    },
  };
}

export default agentSpecsPlugin;
