"""AUTO-GENERATED by scripts/spec_cli.py — do not edit.

Source: agents/disruption_shield/spec.yaml (reward block).
Regenerate: `python scripts/spec_cli.py generate-reward-config`.
"""

from __future__ import annotations

WEIGHTS: dict[str, float] = {
    "early_detection_weight": 1.0,
    "false_positive_weight": 10.0,
    "missed_disruption_weight": 50.0,
    "recovery_speed_weight": 1.0,
}

SCALE: float = 1.0
